/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Strands extends javax.swing.JFrame {

    /**
     * Creates new form Strands
     */
    public Strands() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("GAS Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("ICT Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("ABM Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("HUMMS Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Strands");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame();
        JTable table = new JTable();
        
        
        Object[] columns = {"ICT-Student#","Student Name","Age","Gender"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        
        table.setBackground(Color.BLACK);
        table.setBackground(Color.GRAY);
        Font font = new Font("",1,22);
        table.setFont(font);
        table.setRowHeight(30);
        
        
        
        JTextField textstrands= new JTextField();
        JTextField textname = new JTextField();
        JTextField textage = new JTextField();
        JTextField textgender = new JTextField();
        
        JLabel strands = new JLabel("Student#");
        JLabel name = new JLabel("Name");
        JLabel age = new JLabel("Age");
        JLabel gender = new JLabel("Gender");
        
        
        JButton btnAdd = new JButton("Add");
        JButton btnDelete = new JButton("Delete");
        JButton btnUpdate = new JButton("Update");
        JButton btnClear = new JButton("Clear");
        
        
        strands.setBounds(20, 220, 100, 25);
        name.setBounds(20, 250, 100, 25);
        age.setBounds(20, 280, 100, 25);
        gender.setBounds(20, 310, 100, 25);
        
        textstrands.setBounds(70, 220, 100, 25);
        textname.setBounds(70, 250, 100, 25);
        textage.setBounds(70, 280, 100, 25);
        textgender.setBounds(70, 310, 100, 25);
        
        btnAdd.setBounds(170, 220, 100, 25);
        btnDelete.setBounds(170, 250, 100, 25);
        btnUpdate.setBounds(170, 280, 100, 25);
        btnClear.setBounds(170, 310, 100, 25);
        
        
        
        
        JScrollPane pane = new JScrollPane(table);
        pane.setBounds(0, 0, 880, 200);
        
        frame.setLayout(null);
        
        frame.add(pane);
        
        frame.add(strands);
        frame.add(name);
        frame.add(age);
        frame.add(gender);
        
        frame.add(textstrands);
        frame.add(textname);
        frame.add(textage);
        frame.add(textgender);
        
        frame.add(btnAdd);
        frame.add(btnDelete);
        frame.add(btnUpdate);
        frame.add(btnClear);
        
        
        
        Object[] row = new Object[4];
        btnAdd.addActionListener(new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
            row[0] = textstrands.getText();
            row[1] = textname.getText();
            row[2] = textage.getText();
            row[3] = textgender.getText();
            
            model.addRow(row);
        }
    });
        
        btnDelete.addActionListener(new ActionListener(){
            
            @Override
        public void actionPerformed(ActionEvent e){
            
            int i = table.getSelectedRow();
            if(i >= 0){
               model.removeRow(i);
            }
            else{
                System.out.println("Delete Error");
            }
        }    
        });
        
        table.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int i = table.getSelectedRow();
                textstrands.setText(model.getValueAt(i, 0).toString());
                textname.setText(model.getValueAt(i, 1).toString());
                textage.setText(model.getValueAt(i, 2).toString());
                textgender.setText(model.getValueAt(i, 3).toString());
            }
        });
        
        btnUpdate.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int i = table.getSelectedRow();
                
                if(i >=0)
                {
                    model.setValueAt(textstrands.getText(), i, 0);
                    model.setValueAt(textname.getText(), i, 1);
                    model.setValueAt(textage.getText(), i, 2);
                    model.setValueAt(textgender.getText(), i, 3);
                }
                else{
                    System.out.println("Update Error");
                }
            }
                
        });
        btnClear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                textage.setText(null);
                textgender.setText(null);
                textstrands.setText(null);
                textname.setText(null);
            }
                
        }); 
        
          
        frame.setSize(900,400);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame();
        JTable table = new JTable();
        
        
        Object[] columns = {"ABM-Student#","Student Name","Age","Gender"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        
        table.setBackground(Color.BLACK);
        table.setBackground(Color.GRAY);
        Font font = new Font("",1,22);
        table.setFont(font);
        table.setRowHeight(30);
        
        
        
        JTextField textstrands= new JTextField();
        JTextField textname = new JTextField();
        JTextField textage = new JTextField();
        JTextField textgender = new JTextField();
        
        JLabel strands = new JLabel("Student#");
        JLabel name = new JLabel("Name");
        JLabel age = new JLabel("Age");
        JLabel gender = new JLabel("Gender");
        
        
        JButton btnAdd = new JButton("Add");
        JButton btnDelete = new JButton("Delete");
        JButton btnUpdate = new JButton("Update");
        JButton btnClear = new JButton("Clear");
        
        
        strands.setBounds(20, 220, 100, 25);
        name.setBounds(20, 250, 100, 25);
        age.setBounds(20, 280, 100, 25);
        gender.setBounds(20, 310, 100, 25);
        
        textstrands.setBounds(70, 220, 100, 25);
        textname.setBounds(70, 250, 100, 25);
        textage.setBounds(70, 280, 100, 25);
        textgender.setBounds(70, 310, 100, 25);
        
        btnAdd.setBounds(170, 220, 100, 25);
        btnDelete.setBounds(170, 250, 100, 25);
        btnUpdate.setBounds(170, 280, 100, 25);
        btnClear.setBounds(170, 310, 100, 25);
        
        
        JScrollPane pane = new JScrollPane(table);
        pane.setBounds(0, 0, 880, 200);
        
        frame.setLayout(null);
        
        frame.add(pane);
        
        frame.add(strands);
        frame.add(name);
        frame.add(age);
        frame.add(gender);
        
        frame.add(textstrands);
        frame.add(textname);
        frame.add(textage);
        frame.add(textgender);
        
        frame.add(btnAdd);
        frame.add(btnDelete);
        frame.add(btnUpdate);
        frame.add(btnClear);
        
        Object[] row = new Object[4];
        btnAdd.addActionListener(new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
            row[0] = textstrands.getText();
            row[1] = textname.getText();
            row[2] = textage.getText();
            row[3] = textgender.getText();
            
            model.addRow(row);
        }
    });
        
        btnDelete.addActionListener(new ActionListener(){
            
            @Override
        public void actionPerformed(ActionEvent e){
            
            int i = table.getSelectedRow();
            if(i >= 0){
               model.removeRow(i);
            }
            else{
                System.out.println("Delete Error");
            }
        }    
        });
        
        table.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int i = table.getSelectedRow();
                textstrands.setText(model.getValueAt(i, 0).toString());
                textname.setText(model.getValueAt(i, 1).toString());
                textage.setText(model.getValueAt(i, 2).toString());
                textgender.setText(model.getValueAt(i, 3).toString());
            }
        });
        
        btnUpdate.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int i = table.getSelectedRow();
                
                if(i >=0)
                {
                    model.setValueAt(textstrands.getText(), i, 0);
                    model.setValueAt(textname.getText(), i, 1);
                    model.setValueAt(textage.getText(), i, 2);
                    model.setValueAt(textgender.getText(), i, 3);
                }
                else{
                    System.out.println("Update Error");
                }
            }
                
        });
        
        btnClear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                textage.setText(null);
                textgender.setText(null);
                textstrands.setText(null);
                textname.setText(null);
            }
                
        });
        
        
        frame.setSize(900,400);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame();
        JTable table = new JTable();
        
        
        Object[] columns = {"GAS-Student#","Student Name","Age","Gender"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        
        table.setBackground(Color.BLACK);
        table.setBackground(Color.GRAY);
        Font font = new Font("",1,22);
        table.setFont(font);
        table.setRowHeight(30);
        
        
        
        JTextField textstrands= new JTextField();
        JTextField textname = new JTextField();
        JTextField textage = new JTextField();
        JTextField textgender = new JTextField();
        
        JLabel strands = new JLabel("Student#");
        JLabel name = new JLabel("Name");
        JLabel age = new JLabel("Age");
        JLabel gender = new JLabel("Gender");
        
        
        JButton btnAdd = new JButton("Add");
        JButton btnDelete = new JButton("Delete");
        JButton btnUpdate = new JButton("Update");
        JButton btnClear = new JButton("Clear");
        
        strands.setBounds(20, 220, 100, 25);
        name.setBounds(20, 250, 100, 25);
        age.setBounds(20, 280, 100, 25);
        gender.setBounds(20, 310, 100, 25);
        
        textstrands.setBounds(70, 220, 100, 25);
        textname.setBounds(70, 250, 100, 25);
        textage.setBounds(70, 280, 100, 25);
        textgender.setBounds(70, 310, 100, 25);
        
        btnAdd.setBounds(170, 220, 100, 25);
        btnDelete.setBounds(170, 250, 100, 25);
        btnUpdate.setBounds(170, 280, 100, 25);
        btnClear.setBounds(170, 310, 100, 25);
        
        
        JScrollPane pane = new JScrollPane(table);
        pane.setBounds(0, 0, 880, 200);
        
        frame.setLayout(null);
        
        frame.add(pane);
        
        frame.add(strands);
        frame.add(name);
        frame.add(age);
        frame.add(gender);
        
        frame.add(textstrands);
        frame.add(textname);
        frame.add(textage);
        frame.add(textgender);
        
        frame.add(btnAdd);
        frame.add(btnDelete);
        frame.add(btnUpdate);
        frame.add(btnClear);
        
        Object[] row = new Object[4];
        btnAdd.addActionListener(new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
            row[0] = textstrands.getText();
            row[1] = textname.getText();
            row[2] = textage.getText();
            row[3] = textgender.getText();
            
            model.addRow(row);
        }
    });
        
        btnDelete.addActionListener(new ActionListener(){
            
            @Override
        public void actionPerformed(ActionEvent e){
            
            int i = table.getSelectedRow();
            if(i >= 0){
               model.removeRow(i);
            }
            else{
                System.out.println("Delete Error");
            }
        }    
        });
        
        table.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int i = table.getSelectedRow();
                textstrands.setText(model.getValueAt(i, 0).toString());
                textname.setText(model.getValueAt(i, 1).toString());
                textage.setText(model.getValueAt(i, 2).toString());
                textgender.setText(model.getValueAt(i, 3).toString());
            }
        });
        
        btnUpdate.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int i = table.getSelectedRow();
                
                if(i >=0)
                {
                    model.setValueAt(textstrands.getText(), i, 0);
                    model.setValueAt(textname.getText(), i, 1);
                    model.setValueAt(textage.getText(), i, 2);
                    model.setValueAt(textgender.getText(), i, 3);
                }
                else{
                    System.out.println("Update Error");
                }
            }
                
        });
        btnClear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                textage.setText(null);
                textgender.setText(null);
                textstrands.setText(null);
                textname.setText(null);
            }
        });
        
        
        frame.setSize(900,400);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame();
        JTable table = new JTable();
        
        
        Object[] columns = {"HUMMS-Student#","Student Name","Age","Gender"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        
        table.setBackground(Color.BLACK);
        table.setBackground(Color.GRAY);
        Font font = new Font("",1,22);
        table.setFont(font);
        table.setRowHeight(30);
        
        
        
        JTextField textstrands= new JTextField();
        JTextField textname = new JTextField();
        JTextField textage = new JTextField();
        JTextField textgender = new JTextField();
        
        JLabel strands = new JLabel("Student#");
        JLabel name = new JLabel("Name");
        JLabel age = new JLabel("Age");
        JLabel gender = new JLabel("Gender");
        
        
        JButton btnAdd = new JButton("Add");
        JButton btnDelete = new JButton("Delete");
        JButton btnUpdate = new JButton("Update");
        JButton btnClear = new JButton("Clear");
        
        strands.setBounds(20, 220, 100, 25);
        name.setBounds(20, 250, 100, 25);
        age.setBounds(20, 280, 100, 25);
        gender.setBounds(20, 310, 100, 25);
        
        textstrands.setBounds(70, 220, 100, 25);
        textname.setBounds(70, 250, 100, 25);
        textage.setBounds(70, 280, 100, 25);
        textgender.setBounds(70, 310, 100, 25);
        
        btnAdd.setBounds(170, 220, 100, 25);
        btnDelete.setBounds(170, 250, 100, 25);
        btnUpdate.setBounds(170, 280, 100, 25);
        btnClear.setBounds(170, 310, 100, 25);
        
        JScrollPane pane = new JScrollPane(table);
        pane.setBounds(0, 0, 880, 200);
        
        frame.setLayout(null);
        
        frame.add(pane);
        
        frame.add(strands);
        frame.add(name);
        frame.add(age);
        frame.add(gender);
        
        frame.add(textstrands);
        frame.add(textname);
        frame.add(textage);
        frame.add(textgender);
        
        frame.add(btnAdd);
        frame.add(btnDelete);
        frame.add(btnUpdate);
        frame.add(btnClear);
        
        Object[] row = new Object[4];
        btnAdd.addActionListener(new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
            row[0] = textstrands.getText();
            row[1] = textname.getText();
            row[2] = textage.getText();
            row[3] = textgender.getText();
            
            model.addRow(row);
        }
    });
        
        btnDelete.addActionListener(new ActionListener(){
            
            @Override
        public void actionPerformed(ActionEvent e){
            
            int i = table.getSelectedRow();
            if(i >= 0){
               model.removeRow(i);
            }
            else{
                System.out.println("Delete Error");
            }
        }    
        });
        
        table.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                int i = table.getSelectedRow();
                textstrands.setText(model.getValueAt(i, 0).toString());
                textname.setText(model.getValueAt(i, 1).toString());
                textage.setText(model.getValueAt(i, 2).toString());
                textgender.setText(model.getValueAt(i, 3).toString());
            }
        });
        
        btnUpdate.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int i = table.getSelectedRow();
                
                if(i >=0)
                {
                    model.setValueAt(textstrands.getText(), i, 0);
                    model.setValueAt(textname.getText(), i, 1);
                    model.setValueAt(textage.getText(), i, 2);
                    model.setValueAt(textgender.getText(), i, 3);
                }
                else{
                    System.out.println("Update Error");
                }
            }
                
        });
        btnClear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                textage.setText(null);
                textgender.setText(null);
                textstrands.setText(null);
                textname.setText(null);
            }
        });
        
        
        frame.setSize(900,400);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Strands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Strands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Strands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Strands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Strands().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
